/**
 * AI Thinking Console — Polls real AI trading logs from the database.
 * Shows live AI reasoning as logs are generated by the backend engine.
 */
import { useState, useEffect, useRef } from "react";
import { useTranslation } from "react-i18next";
import { Terminal, X, Brain, Wifi, WifiOff } from "lucide-react";
import { Dialog, DialogContent } from "@/components/ui/dialog";
import { useQuery } from "@tanstack/react-query";

interface ConsoleLog {
  id: string;
  model: string;
  asset: string;
  timeframe: string;
  logType: string;
  content: string;
  tradeId: string | null;
  createdAt: string;
}

function lineColor(type: string): string {
  switch (type) {
    case "system":   return "text-muted-foreground/50";
    case "signal":   return "text-yellow-400/80";
    case "result":   return "text-emerald-400 font-bold";
    default:         return "text-foreground/55";
  }
}

function ts(dateStr: string): string {
  const d = new Date(dateStr);
  return `${d.getHours().toString().padStart(2,"0")}:${d.getMinutes().toString().padStart(2,"0")}:${d.getSeconds().toString().padStart(2,"0")}`;
}

// ─── Main Console Component ───────────────────────────────────────────────────

export function AiThinkingConsole({ model, color, isVisible }: { model: string; color: string; isVisible: boolean }) {
  const scrollRef = useRef<HTMLDivElement>(null);
  const [displayedLines, setDisplayedLines] = useState<ConsoleLog[]>([]);
  const [typingLine, setTypingLine] = useState<{ text: string; type: string } | null>(null);
  const typingQueueRef = useRef<ConsoleLog[]>([]);
  const isTypingRef = useRef(false);
  const cancelRef = useRef(false);
  const seenIdsRef = useRef(new Set<string>());

  const { data: logs = [], dataUpdatedAt } = useQuery<ConsoleLog[]>({
    queryKey: ["ai-sim-logs", model],
    queryFn: async () => {
      const r = await fetch(`/api/ai-sim/logs?model=${encodeURIComponent(model)}&limit=60`);
      if (!r.ok) throw new Error("fetch failed");
      return r.json() as Promise<ConsoleLog[]>;
    },
    enabled: isVisible,
    refetchInterval: 20_000,
    staleTime: 15_000,
    refetchOnWindowFocus: false,
  });

  // When new logs arrive, queue up unseen ones for typewriter
  useEffect(() => {
    if (!isVisible || !logs.length) return;
    // Sort ascending
    const sorted = [...logs].sort((a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime());
    const newLogs = sorted.filter(l => !seenIdsRef.current.has(l.id));

    if (!newLogs.length) return;

    // On first load, show most recent 20 immediately (no typewriter)
    if (seenIdsRef.current.size === 0) {
      const recentBatch = sorted.slice(-20);
      recentBatch.forEach(l => seenIdsRef.current.add(l.id));
      setDisplayedLines(recentBatch);
      // Queue remaining new ones (if any new ones beyond the seed)
      const queuedNew = newLogs.filter(l => !seenIdsRef.current.has(l.id));
      queuedNew.forEach(l => {
        seenIdsRef.current.add(l.id);
        typingQueueRef.current.push(l);
      });
    } else {
      newLogs.forEach(l => {
        seenIdsRef.current.add(l.id);
        typingQueueRef.current.push(l);
      });
    }
    processQueue();
  }, [dataUpdatedAt, isVisible]);

  async function processQueue() {
    if (isTypingRef.current || cancelRef.current) return;
    const next = typingQueueRef.current.shift();
    if (!next) return;

    isTypingRef.current = true;
    const text = next.content;
    const speed = next.logType === "result" ? 22 : next.logType === "system" ? 14 : 16;

    for (let i = 0; i <= text.length; i++) {
      if (cancelRef.current) { isTypingRef.current = false; return; }
      setTypingLine({ text: text.slice(0, i), type: next.logType });
      await new Promise(r => setTimeout(r, speed));
    }

    setDisplayedLines(prev => [...prev.slice(-80), next]);
    setTypingLine(null);
    isTypingRef.current = false;

    const pause = next.logType === "result" ? 600 : 100;
    await new Promise(r => setTimeout(r, pause));
    processQueue();
  }

  useEffect(() => {
    if (!isVisible) {
      cancelRef.current = true;
      setDisplayedLines([]);
      setTypingLine(null);
      typingQueueRef.current = [];
      seenIdsRef.current.clear();
      isTypingRef.current = false;
      return () => {};
    }
    cancelRef.current = false;
    return () => { cancelRef.current = true; };
  }, [isVisible, model]);

  useEffect(() => {
    if (scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
  }, [displayedLines, typingLine]);

  const isLive = logs.length > 0;

  return (
    <div className="rounded-lg overflow-hidden" style={{ background: "rgba(0,0,0,0.5)", border: `1px solid ${color}15` }}>
      <div className="flex items-center gap-2 px-3 py-1.5" style={{ background: "rgba(0,0,0,0.3)", borderBottom: `1px solid ${color}10` }}>
        <Terminal className="h-3 w-3" style={{ color }} />
        <span className="text-[10px] font-mono font-bold" style={{ color }}>{model} Console</span>
        <div className="flex-1" />
        {isLive
          ? <Wifi className="h-2.5 w-2.5 text-emerald-400" />
          : <WifiOff className="h-2.5 w-2.5 text-muted-foreground/40" />
        }
        <span className="text-[9px] font-mono text-muted-foreground/40">
          {typingLine ? "analyzing..." : isLive ? "live" : "connecting..."}
        </span>
      </div>
      <div ref={scrollRef} className="px-3 py-2 h-[240px] overflow-y-auto font-mono text-[10px] leading-relaxed space-y-0.5 scrollbar-hide">
        {displayedLines.map((line) => (
          <div key={line.id} className={lineColor(line.logType)}>
            <span className="text-muted-foreground/25 mr-1.5 select-none">{ts(line.createdAt)}</span>
            {line.content}
          </div>
        ))}
        {typingLine && (
          <div className={lineColor(typingLine.type)}>
            {typingLine.text}<span className="animate-pulse" style={{ color }}>▊</span>
          </div>
        )}
        {displayedLines.length === 0 && !typingLine && (
          <div className="text-muted-foreground/30 animate-pulse text-[10px]">
            Connecting to {model} engine...
          </div>
        )}
      </div>
    </div>
  );
}

// ─── Button + Dialog wrapper ──────────────────────────────────────────────────

export function AiConsoleButton({ model, color }: { model: string; color: string }) {
  const { t } = useTranslation();
  const [open, setOpen] = useState(false);

  return (
    <>
      <button
        onClick={() => setOpen(true)}
        className="w-full flex items-center justify-center gap-2 rounded-xl py-2.5 text-[12px] font-bold transition-all active:scale-[0.98]"
        style={{ background: "rgba(0,0,0,0.35)", border: `1px solid ${color}25`, color }}
        data-testid={`button-console-${model}`}
      >
        <Brain className="h-3.5 w-3.5" />
        {t("aiConsole.console")}
      </button>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent
          className="max-w-md w-full p-0 overflow-hidden"
          style={{
            background: "linear-gradient(160deg, hsl(22,20%,4%), hsl(20,15%,3%))",
            border: `1px solid ${color}22`,
          }}
        >
          <div className="flex items-center justify-between px-4 pt-3 pb-2">
            <div className="flex items-center gap-2">
              <Terminal className="h-4 w-4" style={{ color }} />
              <span className="text-sm font-bold">{model} {t("aiConsole.console")}</span>
            </div>
            <button onClick={() => setOpen(false)} className="text-muted-foreground hover:text-foreground transition-colors">
              <X className="h-4 w-4" />
            </button>
          </div>
          <AiThinkingConsole model={model} color={color} isVisible={open} />
        </DialogContent>
      </Dialog>
    </>
  );
}
